# HTML
# Archive your static HTML project and save it with the build record.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

pool:
  vmImage: ubuntu-latest

steps:
- task: ArchiveFiles@2
  inputs:
    rootFolderOrFile: '$(build.sourcesDirectory)'
    includeRootFolder: false
- task: PublishBuildArtifacts@1
- task: CopyFilesOverSSH@0
  inputs:
    sshEndpoint: 'DEV'
    sourceFolder: '$(build.sourcesDirectory)'
    contents: '**'
    targetFolder: '/deploy'
    readyTimeout: '20000'
- task: SSH@0
  inputs:
    sshEndpoint: 'DEV'
    runOptions: 'inline'
    inline: |
      #Unit Testing
      echo "unit testing started"
      if grep 'Fatel' /deploy/index.html; then
       echo "Test is failed in following number of line"
       sed -n '/Fatel/=' /deploy/index.html
       exit 1
      fi
      
      echo "Test is Successful"
    readyTimeout: '20000'
- task: SSH@0
  inputs:
    sshEndpoint: 'DEV'
    runOptions: 'inline'
    inline: |
      cd /var/www/
       sudo rm -rf html
      cd /var/www/deployments/
      sudo mkdir Dev-$(Build.BuildId)
      sudo cp -r /deploy/* /var/www/deployments/Dev-$(Build.BuildId)
      cd /var/www/
       sudo ln -s deployments/Dev-$(Build.BuildId) html
    readyTimeout: '20000'